const actionTypes = {
  SEARCH_BY_KEYWORD: 'SEARCH_BY_KEYWORD',
  LOAD_MORE_PHOTOS: 'LOAD_MORE_PHOTOS',
  SHOW_DETAIL: 'SHOW_DETAIL',
  HIDE_DETAIL: 'HIDE_DETAIL',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
}

export default actionTypes